server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    path: /error

spring:
  devtools:
    livereload:
      enabled: true
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        #use_sql_comments: true
    open-in-view: false
  
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: Google Username
    password: Google Password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
  
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: Google OAuth 2.0 Client-Id
            client-secret: Google OAuth 2.0 Client-Secret
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate.sql: debug
    #org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

file:
  upload:
    location: Upload Path

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop